name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-api:
    name: Build and Deploy api
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: 14traits/flavorday-api
        dockerfile: /Dockerfile
        tags: v.0.1