---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/locations":
    post:
      summary: Create an location
      tags:
      - Locations
      parameters: []
      responses:
        '201':
          description: location created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                latitude:
                  type: number
                  format: float
                longitude:
                  type: number
                  format: float
                title:
                  type: string
                address:
                  type: string
                city:
                  type: string
                state:
                  type: string
                postal_code:
                  type: integer
                cl_id:
                  type: integer
                uid:
                  type: integer
              required:
              - title
              - postal_code
  "/api/v1/locations/{id}":
    get:
      summary: Retrieves a location
      tags:
      - Locations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  title:
                    type: string
                  address:
                    type: string
                  city:
                    type: string
                  state:
                    type: string
                  postal_code:
                    type: integer
                  cl_id:
                    type: integer
                  uid:
                    type: integer
                required:
                - title
        '404':
          description: location not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
