
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: john
  #username: flavorapp
  #password: FlavorDayApp@2022
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flavor_day_api_development
  # host: localhost
  # port: 5432

test:
  <<: *default
  database: flavor_day_api_test

# production:
#   <<: *default
#   database: flavor_day_api_production
#   username: flavor_day_api
#   password: <%= ENV["FLAVOR_DAY_API_DATABASE_PASSWORD"] %>
