
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flavor_day_api_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: flavor_day_api_test

production:
  <<: *default
  database: flavor_day_api_production
  host: 0.0.0.0
  port: 5432
  username: flavor_day
  password: <%= ENV["FLAVOR_DAY_API_DATABASE_PASSWORD"] %>
